
const errors = {
    SYMBOL_ALREADY_EXISTS: 'SYMBOL_ALREADY_EXISTS',
    FATHER_DOES_NOT_EXISTS: 'FATHER_DOES_NOT_EXISTS',
    SYMBOL_DOES_NOT_EXISTS: 'SYMBOL_DOES_NOT_EXISTS',
    SYMBOL_HAS_CHILDREN: 'SYMBOL_HAS_CHILDREN',
}

module.exports = {
    errors
};
